version: "3.8"

services:
  warnings-discord-bot:
    build: .
    image: warnings-discord-bot
    container_name: warnings-discord-bot
    restart: unless-stopped
    volumes:
      - "/etc/timezone:/etc/timezone:ro" # Set timezone to host timezone.
      - "/etc/localtime:/etc/localtime:ro" # Set time to host time.
      - ./config/config.json:/config/config.json # Include bot config.
    env_file:
      - .env
